fullnameOverride: promtail

image:
  repository: grafana/promtail
  tag: v0.4.0-arm

pipelineStages:
  - cri: {}

loki:
  serviceName: loki
  servicePort: 3100
  serviceScheme: http

volumes:
  - name: containers
    hostPath:
      path: /var/log/containers
  - name: pods
    hostPath:
      path: /var/log/pods

volumeMounts:
  - name: containers
    mountPath: /var/log/containers
    readOnly: true
  - name: pods
    mountPath: /var/log/pods
    readOnly: true