apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: promtail
  namespace: logging
  annotations:
    fluxcd.io/automated: "false"
spec:
  chart:
    repository: https://grafana.github.io/loki/charts
    name: promtail
    version: 0.16.0
  valuesFrom:
    - externalSourceRef:
        url: https://raw.githubusercontent.com/REBELinBLUE/k8s-on-hypriot/master/deployments/logging/promtail/promtail-values.yaml