---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubeview
  namespace: infra
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubeview-role
rules:
  - apiGroups: ["extensions"]
    resources: ["ingresses"]
    verbs: ["get", "list"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets", "daemonsets", "statefulsets"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods", "ingresses", "events", "endpoints", "namespaces", "nodes", "persistentvolumes", "persistentvolumeclaims", "resourcequotas", "services"]
    verbs: ["get", "list"]
  - nonResourceURLs: ["*"]
    verbs: ["get", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubeview
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubeview-role
subjects:
  - kind: ServiceAccount
    name: kubeview
    namespace: infra
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: kubeview
  namespace: infra
  labels:
    app: kubeview
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubeview
  template:
    metadata:
      labels:
        app: kubeview
        blinktShow: "true"
        blinktColor: "00ff00"
    spec:
      serviceAccountName: kubeview
      containers:
        - name: kubeview-containers
          image: rebelinblue/kubeview:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          resources:
            limits:
              memory: "128M"
              cpu: "0.1"
---
kind: Service
apiVersion: v1
metadata:
  name: kubeview
  namespace: infra
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  selector:
    app: kubeview
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kubeview
  namespace: infra
  annotations:
    ingress.kubernetes.io/auth-type: forward
    ingress.kubernetes.io/auth-url: "http://traefik-forward-auth.infra.svc:4181"
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    traefik.ingress.kubernetes.io/redirect-permanent: "true"
    kubernetes.io/ingress.class: traefik
    forecastle.stakater.com/expose: "true"
    forecastle.stakater.com/group: "Miscellaneous"
    forecastle.stakater.com/icon: "https://raw.githubusercontent.com/benc-uk/kubeview/master/web/client/src/assets/logo.png"
    forecastle.stakater.com/appName: KubeView
spec:
  rules:
    - host: kubeview.cluster.rebelinblue.com
      http:
        paths:
          - path: /
            backend:
              serviceName: kubeview
              servicePort: 80
