---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reloader
  namespace: infra
  labels:
    app: reloader
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: reloader
  template:
    metadata:
      labels:
        app: reloader
    spec:
      containers:
        - name: reloader
          image: "rebelinblue/reloader:1.0.0"
          imagePullPolicy: IfNotPresent
      serviceAccountName: reloader

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: reloader-role
  namespace: infra
  labels:
    app: reloader
rules:
  - apiGroups: [""]
    resources: ["secrets", "configmaps"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["extensions", "apps"]
    resources: ["deployments", "daemonsets", "statefulsets"]
    verbs: ["get", "list", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: reloader-role-binding
  namespace: infra
  labels:
    app: reloader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: reloader-role
subjects:
  - kind: ServiceAccount
    name: reloader
    namespace: infra
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: reloader
  namespace: infra
  labels:
    app: reloader

