apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: kube-state-metrics
  namespace: kube-system
  annotations:
    fluxcd.io/automated: "false"
    fluxcd.io/tag.chart-image: semver:~1.8
spec:
  releaseName: kube-state-metrics
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: kube-state-metrics
    version: 2.5.0
  values:
    priorityClassName: system-cluster-critical
    image:
      repository: cyrilix/kube-state-metrics
      tag: 1.8.0
