apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: kubeview
  namespace: apps
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: kubeview
  chart:
    git: git@github.com:REBELinBLUE/kubeview.git
    path: deployments/helm/kubeview
    ref: configmaps
  valuesFrom:
    - externalSourceRef:
        url: https://raw.githubusercontent.com/REBELinBLUE/k8s-on-hypriot/master/deployments/apps/kubeview/kubeview-values.yaml
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: kubeview-images
  namespace: apps
  annotations:
    kubernetes.io/ingress.class: traefik
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
    - host: kubeview.cluster.rebelinblue.com
      http:
        paths:
          - path: /img
            backend:
              serviceName: kubeview
              servicePort: 80
          - path: /css
            backend:
              serviceName: kubeview
              servicePort: 80
          - path: /js
            backend:
              serviceName: kubeview
              servicePort: 80
  tls:
    - hosts:
        - kubeview.cluster.rebelinblue.com
      secretName: kubeview-tls