---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubeview
  namespace: apps
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubeview-role
rules:
  - apiGroups: ["extensions"]
    resources: ["ingresses"]
    verbs: ["get", "list"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets", "daemonsets", "statefulsets"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods", "ingresses", "events", "endpoints", "namespaces", "nodes", "persistentvolumes", "persistentvolumeclaims", "resourcequotas", "services"]
    verbs: ["get", "list"]
  - nonResourceURLs: ["*"]
    verbs: ["get", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubeview
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubeview-role
subjects:
  - kind: ServiceAccount
    name: kubeview
    namespace: apps
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: kubeview
  namespace: apps
  labels:
    app: kubeview
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubeview
  template:
    metadata:
      labels:
        app: kubeview
    spec:
      serviceAccountName: kubeview
      containers:
        - name: kubeview-containers
          image: rebelinblue/kubeview:v0.1.9
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          resources:
            limits:
              memory: "128M"
              cpu: "0.1"
---
kind: Service
apiVersion: v1
metadata:
  name: kubeview
  namespace: apps
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  selector:
    app: kubeview
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kubeview
  namespace: apps
  annotations:
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    ingress.kubernetes.io/auth-type: forward
    ingress.kubernetes.io/auth-trust-headers: "true"
    ingress.kubernetes.io/ssl-redirect: "true"
    ingress.kubernetes.io/auth-url: http://traefik-forward-auth.infra.svc
    ingress.kubernetes.io/auth-response-headers: X-Forwarded-User
spec:
  rules:
    - host: kubeview.cluster.rebelinblue.com
      http:
        paths:
          - path: /
            backend:
              serviceName: kubeview
              servicePort: 80
  tls:
    - hosts:
        - kubeview.cluster.rebelinblue.com
      secretName: kubeview-tls
