---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cainjector
  namespace: cert-manager
  labels:
    app: cainjector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cainjector
  template:
    metadata:
      labels:
        app: cainjector
    spec:
      serviceAccountName: cainjector
      containers:
        - name: cainjector
          image: "quay.io/jetstack/cert-manager-cainjector-arm:v0.11.0"
          imagePullPolicy: IfNotPresent
          args:
          - --v=2
          - --leader-election-namespace=kube-system
          env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
            
