apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: node-exporter
  namespace: kube-system
  annotations:
    fluxcd.io/automated: "false"
    fluxcd.io/tag.chart-image: semver:~0
spec:
  releaseName: node-exporter
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: prometheus-node-exporter
    version: 1.8.1
  values:
    nameOverride: node-exporter
    image:
      repository: prom/node-exporter
      tag: v0.18.1
    priorityClassName: system-node-critical
