apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: node-exporter
  namespace: kube-system
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: node-exporter
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: prometheus-node-exporter
    version: 1.8.1
  valuesFrom:
    - externalSourceRef:
        url: https://raw.githubusercontent.com/REBELinBLUE/k8s-on-hypriot/master/deployments/kube-system/node-exporter/node-exporter-values.yaml
