---
apiVersion: v1
kind: ConfigMap
metadata:
  name: speedtest
  namespace: monitoring
  labels:
    app: speedtest
data:
  config.ini: |
    [GENERAL]
    Delay = 7200

    [INFLUXDB]
    Address = influxdb.monitoring.svc
    Port = 8086
    Database = speedtests
    Username =
    Password =
    Verify_SSL = False

    [SPEEDTEST]
    Server =

    [LOGGING]
    Level = info
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: speedtest
  namespace: monitoring
  labels:
    app: speedtest
spec:
  selector:
    matchLabels:
      app: speedtest
  replicas: 0
  template:
    metadata:
      labels:
        app: speedtest
    spec:
      nodeSelector:
        beta.kubernetes.io/arch: arm
        node-role.kubernetes.io/master: "true"
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
      containers:
        - name: speedtest
          image: rebelinblue/speedtest-for-influxdb-and-grafana:latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: speedtest
              mountPath: /src/config.ini
              subPath: config.ini
      volumes:
        - name: speedtest
          configMap:
            name: speedtest
            items:
              - key: config.ini
                path: config.ini
