---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tiller-deploy
  namespace: kube-system
  labels:
    app: helm
    name: tiller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: helm
        name: tiller
    spec:
      nodeSelector:
        beta.kubernetes.io/arch: arm
      automountServiceAccountToken: true
      serviceAccountName: tiller
      containers:
        - name: tiller
          image: jessestuart/tiller
          imagePullPolicy: IfNotPresent
          env:
            - name: TILLER_NAMESPACE
              value: kube-system
            - name: TILLER_HISTORY_MAX
              value: "0"
          livenessProbe:
            httpGet:
              path: /liveness
              port: 44135
            initialDelaySeconds: 1
            timeoutSeconds: 1
          ports:
            - containerPort: 44134
              name: tiller
            - containerPort: 44135
              name: http
          readinessProbe:
            httpGet:
              path: /readiness
              port: 44135
            initialDelaySeconds: 1
            timeoutSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  name: tiller-deploy
  namespace: kube-system
  labels:
    app: helm
    name: tiller
spec:
  ports:
    - name: tiller
      port: 44134
      targetPort: tiller
  selector:
    app: helm
    name: tiller
---