---
apiVersion: v1
kind: Secret
metadata:
  name: consul-gossip-key
  namespace: infra
  labels:
    app: consul
type: Opaque
data:
  gossip-key: c1BsdW1QL1cyOUh6U2xjdlBxME1uR3d4YWtRbTRHR29acHZaajJXeDl6cz0K
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: consul-config
  namespace: infra
  labels:
    app: consul
data:
  consul.hcl: |-
    addresses = {
      https = "0.0.0.0"
    }
    ports = {
      http = 8500,
      server = 9300,
      https = -1
    }
    performance = {
      raft_multiplier = 1
    }
    primary_datacenter = "dc1"
    skip_leave_on_interrupt = true,
    leave_on_terminate = false
    rejoin_after_leave = true
    log_level = "INFO"
    disable_remote_exec = true
---
apiVersion: v1
kind: Service
metadata:
  name: consul
  namespace: infra
  labels:
    app: consul
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  type: ClusterIP
  selector:
    app: consul
  ports:
    - name: http
      port: 8500
    - name: rpc
      port: 8400
    - name: serflan-tcp
      protocol: "TCP"
      port: 8301
    - name: serflan-udp
      protocol: "UDP"
      port: 8301
    - name: serfwan-tcp
      protocol: "TCP"
      port: 8302
    - name: serfwan-udp
      protocol: "UDP"
      port: 8302
    - name: server
      port: 8300
    - name: consuldns-tcp
      port: 8600
    - name: consuldns-udp
      protocol: "UDP"
      port: 8600
---
apiVersion: v1
kind: Service
metadata:
  name: consul-ui
  namespace: infra
  labels:
    app: consul
spec:
  type: ClusterIP
  selector:
    app: consul
  ports:
    - name: http
      port: 8500
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: consul
  namespace: infra
  labels:
    app: consul
spec:
  serviceName: "consul"
  replicas: 3
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: consul
  template:
    metadata:
      name: consul
      labels:
        app: consul
    spec:
      securityContext:
        fsGroup: 1000
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: consul
              topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 10
      containers:
        - name: consul
          image: consul:1.6.1
          imagePullPolicy: IfNotPresent
          ports:
            - name: server
              containerPort: 8300
              protocol: "TCP"
            - name: serflan-tcp
              containerPort: 8301
              protocol: "TCP"
            - name: serflan-udp
              containerPort: 8301
              protocol: "UDP"
            - name: serfwan-tcp
              containerPort: 8302
              protocol: "TCP"
            - name: serfwan-udp
              containerPort: 8302
              protocol: "UDP"
            - name: rpc
              containerPort: 8400
              protocol: "TCP"
            - name: http
              containerPort: 8500
              protocol: "TCP"
            - name: consuldns-tcp
              containerPort: 8600
              protocol: "TCP"
            - name: consuldns-udp
              containerPort: 8600
              protocol: "UDP"
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CONSUL_CLUSTER_SIZE
              value: "3"
            - name: CONSUL_STATEFULSET_NAME
              value: "consul"
            - name: CONSUL_DNS_PORT
              value: "8600"
            - name: CONSUL_GOSSIP_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: consul-gossip-key
                  key: gossip-key
            - name: CONSUL_DATACENTER_NAME
              value: "dc1"
            - name: CONSUL_DOMAIN
              value: "cluster.local"
            - name: CONSUL_HTTP_SSL_VERIFY
              value: "false"
            - name: CONSUL_HTTP_SSL
              value: "false"
          args:
            - "agent"
            - "-server"
            - "-ui"
            - "-bootstrap-expect=$(CONSUL_CLUSTER_SIZE)"
            - "-node=$(POD_NAME)"
            - "-datacenter=$(CONSUL_DATACENTER_NAME)"
            - "-data-dir=/var/lib/consul"
            - "-config-dir=/consul/config"
            - "-config-file=/etc/consul/config/consul.hcl"
            - "-log-level=INFO"
            - "-client=0.0.0.0"
            - "-bind=0.0.0.0"
            - "-advertise=$(POD_IP)"
            - "-enable-script-checks=true"
            - "-disable-host-node-id"
            - "-retry-join=$(CONSUL_STATEFULSET_NAME)-0.$(CONSUL_STATEFULSET_NAME).$(POD_NAMESPACE).svc.$(CONSUL_DOMAIN)"
            - "-retry-join=$(CONSUL_STATEFULSET_NAME)-1.$(CONSUL_STATEFULSET_NAME).$(POD_NAMESPACE).svc.$(CONSUL_DOMAIN)"
            - "-retry-join=$(CONSUL_STATEFULSET_NAME)-2.$(CONSUL_STATEFULSET_NAME).$(POD_NAMESPACE).svc.$(CONSUL_DOMAIN)"
            - "-encrypt=$(CONSUL_GOSSIP_ENCRYPTION_KEY)"
          livenessProbe:
            exec:
              command:
                - consul
                - members
                - -http-addr=http://127.0.0.1:8500
            initialDelaySeconds: 60
            timeoutSeconds: 5
          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - consul leave
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - name: datadir
              mountPath: /var/lib/consul
            - name: config
              mountPath: /etc/consul/config
      volumes:
        - name: config
          configMap:
            name: consul-config
            items:
              - key: consul.hcl
                path: consul.hcl
  volumeClaimTemplates:
    - metadata:
        name: datadir
      spec:
        accessModes:
          - ReadWriteMany
        resources:
          requests:
            storage: 20Gi
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: consul-ui
  namespace: infra
  labels:
    app: consul
  annotations:
    ingress.kubernetes.io/auth-type: forward
    ingress.kubernetes.io/auth-url: "http://traefik-forward-auth.infra.svc:4181"
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    traefik.ingress.kubernetes.io/redirect-permanent: "true"
    kubernetes.io/ingress.class: traefik
    forecastle.stakater.com/expose: "true"
    forecastle.stakater.com/group: "Miscellaneous"
    forecastle.stakater.com/icon: "https://www.consul.io/assets/images/og-image-6ef0ad8b.png"
    forecastle.stakater.com/appName: Consul
spec:
  rules:
    - host: consul.cluster.rebelinblue.com
      http:
        paths:
          - backend:
              serviceName: consul-ui
              servicePort: 8500
            path: /
