git:
  url: "git@github.com:rebelinblue/k3s-on-raspbian.git"
  branch: master
  path: deployments
  readonly: true

image:
  repository: rebelinblue/flux
  tag: 1.21.0
  pullPolicy: Always

registry:
  rps: 1
  burst: 1

sync:
  state: secret

memcached:
  enabled: true

additionalArgs:
  - --connect=ws://fluxcloud

prometheus:
  enabled: true
  serviceMonitor:
    create: true

syncGarbageCollection:
  enabled: true
  dry: true

resources:
  limits:
    cpu: 300m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 64Mi
