apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: flux
  namespace: flux
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: flux
  chart:
    repository: https://charts.fluxcd.io/
    name: flux
    version: 1.0.0
  valuesFrom:
    - externalSourceRef:
        url: https://raw.githubusercontent.com/REBELinBLUE/k8s-on-hypriot/master/deployments/flux/flux/flux-values.yaml