ingress:
  enabled: true
  path: /
  hosts:
    - registry.cluster.rebelinblue.com
  annotations:
    kubernetes.io/ingress.class: traefik
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
  tls:
    - hosts:
        - registry.cluster.rebelinblue.com
      secretName: docker-registry-tls

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/path: "/metrics"
  prometheus.io/port: "5000"

persistence:
  storageClass: nfs-hdd
  enabled: true

configData:
  version: 0.1
  log:
    fields:
      service: registry
  storage:
    cache:
      blobdescriptor: inmemory
  http:
    addr: :5000
    debug:
      prometheus:
        enabled: true
    headers:
      X-Content-Type-Options: [nosniff]
  health:
    storagedriver:
      enabled: true
      interval: 10s
      threshold: 3

secrets:
  haSharedSecret: docker-registry