fullnameOverride: grafana

image:
  repository: grafana/grafana
  tag: 6.5.2

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    ingress.kubernetes.io/auth-type: forward
    ingress.kubernetes.io/auth-url: http://traefik-forward-auth.infra.svc
    ingress.kubernetes.io/auth-response-headers: X-Forwarded-User
  hosts:
    - grafana.cluster.rebelinblue.com
  tls:
    - hosts:
        - grafana.cluster.rebelinblue.com
      secretName: grafana-tls

persistence:
  enabled: true
  storageClassName: nfs-hdd

initChownData:
  enabled: false

testFramework:
  enabled: false

plugins:
  - grafana-piechart-panel

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        url: http://loki.logging.svc:3100
        access: proxy
        editable: false
        isDefault: true
      - name: Prometheus
        type: prometheus
        url: http://prometheus.monitoring.svc:8080
        access: proxy
        editable: false
        isDefault: false
      - name: Speedtests
        type: influxdb
        database: speedtests
        url: http://influxdb.monitoring.svc:8086
        access: proxy
        editable: false
        isDefault: false

grafana.ini:
  paths:
    data: /var/lib/grafana/data
    logs: /var/log/grafana
    plugins: /var/lib/grafana/plugins
    provisioning: /etc/grafana/provisioning
  analytics:
    check_for_updates: true
  log:
    mode: console
  grafana_net:
    url: https://grafana.net
  alerting:
    enabled: false
  users:
    allow_org_create: false
    allow_sign_up: false
  auth:
    disable_login_form: true
    disable_signout_menu: true
  auth.anonymous:
    enabled: true
    org_role: Editor
  auth.basic:
    enabled: false

downloadDashboardsImage:
  repository: lucashalbert/curl
  tag: arm32v6-7.67.0-r0

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: true
      editable: true
      options:
        path: /var/lib/grafana/dashboards/default
    - name: 'kubernetes'
      orgId: 1
      folder: 'Kubernetes'
      type: file
      disableDeletion: true
      editable: true
      options:
        path: /var/lib/grafana/dashboards/kubernetes

dashboards:
  default:
    speedtest:
      url: https://raw.githubusercontent.com/REBELinBLUE/k8s-on-hypriot/master/deployments/monitoring/grafana/dashboards/General/Speedtest.json
    certmanager:
      url: https://raw.githubusercontent.com/REBELinBLUE/k8s-on-hypriot/master/deployments/monitoring/grafana/dashboards/General/CertManager.json
    traefik:
      url: https://raw.githubusercontent.com/REBELinBLUE/k8s-on-hypriot/master/deployments/monitoring/grafana/dashboards/General/Traefik.json
  kubernetes:
    apps:
      url: https://raw.githubusercontent.com/REBELinBLUE/k8s-on-hypriot/master/deployments/monitoring/grafana/dashboards/Kubernetes/Apps.json
    clusterMonitoring:
      url: https://raw.githubusercontent.com/REBELinBLUE/k8s-on-hypriot/master/deployments/monitoring/grafana/dashboards/Kubernetes/ClusterMonitoring.json
    clusterMonitoring2:
      url: https://raw.githubusercontent.com/REBELinBLUE/k8s-on-hypriot/master/deployments/monitoring/grafana/dashboards/Kubernetes/ClusterMonitoring2.json
    deployments:
      url: https://raw.githubusercontent.com/REBELinBLUE/k8s-on-hypriot/master/deployments/monitoring/grafana/dashboards/Kubernetes/Deployments.json
    nodes:
      url: https://raw.githubusercontent.com/REBELinBLUE/k8s-on-hypriot/master/deployments/monitoring/grafana/dashboards/Kubernetes/Nodes.json
    nodes2:
      url: https://raw.githubusercontent.com/REBELinBLUE/k8s-on-hypriot/master/deployments/monitoring/grafana/dashboards/Kubernetes/Nodes2.json
    pods:
      url: https://raw.githubusercontent.com/REBELinBLUE/k8s-on-hypriot/master/deployments/monitoring/grafana/dashboards/Kubernetes/Pods.json
