apiVersion: v1
data:
  grafana.ini: |-
    [auth.anonymous]
    enabled = true
    org_role = Editor
    [auth.basic]
    enabled = false
    [session]
    provider = memory
    [alerting]
    enabled = false
    [users]
    allow_org_create = false
    allow_sign_up = false
    [log]
    mode = console
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: monitoring
