apiVersion: v1
kind: Namespace
metadata:
  name: cheese
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: stilton
  namespace: cheese
  labels:
    app: cheese
    cheese: stilton
spec:
  replicas: 2
  selector:
    matchLabels:
      k8s-app: traefik-ingress-lb
      app: cheese
      task: stilton
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress-lb
        app: cheese
        task: stilton
        version: v0.0.1
    spec:
      containers:
        - name: cheese
          image: errm/cheese:stilton
          resources:
            requests:
              cpu: 100m
              memory: 50Mi
            limits:
              cpu: 100m
              memory: 50Mi
          ports:
            - containerPort: 80
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: cheddar
  namespace: cheese
  labels:
    app: cheese
    cheese: cheddar
spec:
  replicas: 2
  selector:
    matchLabels:
      k8s-app: traefik-ingress-lb
      app: cheese
      task: cheddar
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress-lb
        app: cheese
        task: cheddar
        version: v0.0.1
    spec:
      containers:
        - name: cheese
          image: errm/cheese:cheddar
          resources:
            requests:
              cpu: 100m
              memory: 50Mi
            limits:
              cpu: 100m
              memory: 50Mi
          ports:
            - containerPort: 80
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: wensleydale
  namespace: cheese
  labels:
    app: cheese
    cheese: wensleydale
spec:
  replicas: 2
  selector:
    matchLabels:
      k8s-app: traefik-ingress-lb
      app: cheese
      task: wensleydale
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress-lb
        app: cheese
        task: wensleydale
        version: v0.0.1
    spec:
      containers:
        - name: cheese
          image: errm/cheese:wensleydale
          resources:
            requests:
              cpu: 100m
              memory: 50Mi
            limits:
              cpu: 100m
              memory: 50Mi
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: stilton
  namespace: cheese
spec:
  ports:
    - name: http
      targetPort: 80
      port: 80
  selector:
    k8s-app: traefik-ingress-lb
    app: cheese
    task: stilton
---
apiVersion: v1
kind: Service
metadata:
  name: cheddar
  namespace: cheese
spec:
  ports:
    - name: http
      targetPort: 80
      port: 80
  selector:
    k8s-app: traefik-ingress-lb
    app: cheese
    task: cheddar
---
apiVersion: v1
kind: Service
metadata:
  name: wensleydale
  namespace: cheese
spec:
  ports:
    - name: http
      targetPort: 80
      port: 80
  selector:
    k8s-app: traefik-ingress-lb
    app: cheese
    task: wensleydale
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cheeses
  namespace: cheese
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/frontend-entry-points: http
    traefik.frontend.rule.type: PathPrefixStrip
spec:
  rules:
    - host: cheeses.cluster.local
      http:
        paths:
          - path: /stilton
            backend:
              serviceName: stilton
              servicePort: http
          - path: /cheddar
            backend:
              serviceName: cheddar
              servicePort: http
          - path: /wensleydale
            backend:
              serviceName: wensleydale
              servicePort: http