apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: influxdb
  namespace: monitoring
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: influxdb
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: influxdb
    version: 3.0.2
  valuesFrom:
    - externalSourceRef:
        url: https://raw.githubusercontent.com/REBELinBLUE/k8s-on-hypriot/master/deployments/monitoring/influxdb/influxdb-values.yaml
