apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
  namespace: media
  labels:
    app: plex
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      labels:
        app: plex
    spec:
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
      nodeSelector:
        beta.kubernetes.io/arch: arm
        node-role.kubernetes.io/master: "true"
      hostNetwork: true
      containers:
        - env:
            - name: TZ
              value: Europe/London
            - name: PMS_INTERNAL_ADDRESS
              value: http://plex:32400
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          image: linuxserver/plex:arm32v7-latest
          imagePullPolicy: IfNotPresent
#          livenessProbe:
#            failureThreshold: 3
#            httpGet:
#              path: /identity
#              port: 32400
#              scheme: HTTP
#            initialDelaySeconds: 10
#            periodSeconds: 10
#            successThreshold: 1
#            timeoutSeconds: 10
          name: plex
          ports:
            - name: pms
              containerPort: 32400
              hostPort: 32400
              protocol: TCP
            - name: dlna
              containerPort: 1900
              hostPort: 1900
              protocol: UDP
            - name: control
              containerPort: 3005
              hostPort: 3005
              protocol: TCP
            - name: avahi
              containerPort: 5353
              hostPort: 5353
              protocol: UDP
            - name: discovery0
              containerPort: 32410
              hostPort: 32410
              protocol: UDP
            - name: discovery2
              containerPort: 32412
              hostPort: 32412
              protocol: UDP
            - name: discovery3
              containerPort: 32413
              hostPort: 32413
              protocol: UDP
            - name: discovery4
              containerPort: 32414
              hostPort: 32414
              protocol: UDP
            - name: dlna2
              containerPort: 32469
              hostPort: 32469
              protocol: TCP
#          readinessProbe:
#            failureThreshold: 3
#            httpGet:
#              path: /identity
#              port: 32400
#              scheme: HTTP
#            initialDelaySeconds: 15
#            periodSeconds: 10
#            successThreshold: 1
#            timeoutSeconds: 5
          volumeMounts:
            - name: media
              mountPath: /config
              subPath: plex
            - name: files
              mountPath: /media/NAS
              readOnly: true
      hostname: plex
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: media
        - name: files
          nfs:
            path: /nfs/Media
            server: 192.168.1.112
---
apiVersion: v1
kind: Service
metadata:
  name: plex
  namespace: media
  labels:
    app: plex
spec:
  type: ClusterIP
  ports:
    - name: pms
      port: 32400
      targetPort: 32400
  selector:
    app: plex
