---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
  namespace: vault
  labels:
    app: vault
data:
  vault.hcl: |-
    storage "consul" {
        address = "127.0.0.1:8500"
        path = "vault/"
        scheme = "http"
        service = "vault"
        service_tags = "vault,production"
        session_ttl = "60s"
        disable_registration = "true"
    }
    listener "tcp" {
        address = "0.0.0.0:8200"
        tls_disable = 1
    }
    telemetry {
      prometheus_retention_time = "30s",
      disable_hostname = true
    }
    api_addr = "http://0.0.0.0:8200"
    cluster_address = "http://0.0.0.0:8201"
    disable_mlock = true
    ui = true
    max_lease_ttl = "10h"
    default_lease_ttl = "10h"
    cluster_name = "pi-vault"
  consul.json: |-
    {}
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-unseal-keys
type: Opaque
data:
  VAULT_UNSEAL_KEY_1: RlJFNHlxbEIyNUYzRllHYlUwNUt2MXFQckpLakRTYnBrUEg0bWVaOEJsdVY=
  VAULT_UNSEAL_KEY_2: Wk1tMGViNk1tMnZpTUo0clNRaUUzT3AyUEZOSUdNS1JNS2VtQkVxaG10WSs=
  VAULT_UNSEAL_KEY_3: S3dGNzYzMVFIWkRnVndoLzljMnhPaWczVEt3bjl5Ukt1Nm8raFJjdDgwTHk=
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault
  namespace: vault
  labels:
    app: vault
---
apiVersion: v1
kind: Service
metadata:
  name: vault
  namespace: vault
  labels:
    app: vault
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  type: ClusterIP
  selector:
    app: vault
  publishNotReadyAddresses: true
  ports:
    - name: api
      protocol: TCP
      port: 8200
      targetPort: 8200
    - name: cluster
      protocol: TCP
      port: 8201
      targetPort: 8201
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: vault
  namespace: vault
  labels:
    app: vault
spec:
  serviceName: "vault"
  replicas: 2
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      name: vault
      labels:
        app: vault
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: vault
              topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 10
      containers:
        - name: vault
          image: rebelinblue/vault:1.2.3
          imagePullPolicy: Always
          ports:
            - name: api
              containerPort: 8200
              protocol: "TCP"
            - name: cluster
              containerPort: 8201
              protocol: "TCP"
            - name: replication
              containerPort: 8202
              protocol: "TCP"
          env:
            - name: ENVIRONMENT
              value: production
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: VAULT_ADDR
              value: "http://$(POD_IP):8200"
            - name: VAULT_CLUSTER_ADDR
              value: "http://$(POD_IP):8201"
            - name: VAULT_LOG_LEVEL
              value: "debug"
            - name: VAULT_API_ADDR
              value: "http://$(POD_IP):8200"
            - name: SKIP_CHOWN
              value: "true"
            - name: VAULT_UNSEAL_KEY_1
              valueFrom:
                secretKeyRef:
                  name: vault-unseal-keys
                  key: VAULT_UNSEAL_KEY_1
            - name: VAULT_UNSEAL_KEY_2
              valueFrom:
                secretKeyRef:
                  name: vault-unseal-keys
                  key: VAULT_UNSEAL_KEY_2
            - name: VAULT_UNSEAL_KEY_3
              valueFrom:
                secretKeyRef:
                  name: vault-unseal-keys
                  key: VAULT_UNSEAL_KEY_3
          livenessProbe:
            httpGet:
              path: /v1/sys/health?standbyok=true&uninitcode=204&sealedcode=204&
              port: 8200
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 5
            httpGet:
              path: /v1/sys/health?standbyok=true&uninitcode=204&sealedcode=204&
              port: 8200
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 5
          securityContext:
            readOnlyRootFilesystem: true
            capabilities:
              add:
                - IPC_LOCK
          volumeMounts:
            - name: vault-config-file
              mountPath: /vault/config/vault.hcl
              subPath: vault.hcl
            - name: vault-root
              mountPath: /root/
            - name: vault-temp
              mountPath: /tmp/
        - name: consul-client
          image: consul:1.6.1
          imagePullPolicy: IfNotPresent
          securityContext:
            readOnlyRootFilesystem: true
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CONSUL_GOSSIP_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: consul-gossip-key
                  key: gossip-key
            - name: CONSUL_DATACENTER_NAME
              value: "dc1"
            - name: CONSUL_DOMAIN
              value: "cluster.local"
          command:
            - "consul"
          args:
            - "agent"
            - "-node=$(POD_NAME)"
            - "-datacenter=$(CONSUL_DATACENTER_NAME)"
            - "-client=0.0.0.0"
            - "-bind=0.0.0.0"
            - "-data-dir=/var/lib/consul"
            - "-config-dir=/consul/config"
            - "-domain=$(CONSUL_DOMAIN)"
            - "-retry-join=$(CONSUL_SERVICE_HOST)"
            - "-disable-host-node-id"
            - "-encrypt=$(CONSUL_GOSSIP_ENCRYPTION_KEY)"
          resources:
            limits:
              cpu: "300m"
              memory: 256Mi
            requests:
              cpu: "150m"
              memory: 128Mi
          volumeMounts:
            - name: consul-data
              mountPath: /var/lib/consul
            - name: vault-config-file
              mountPath: /consul/config/consul.json
              subPath: consul.json
      serviceAccountName: "vault"
      volumes:
        - name: vault-config-file
          configMap:
            name: vault-config
        - name: vault-root
          emptyDir: {}
        - name: vault-temp
          emptyDir: {}
        - name: consul-data
          emptyDir: {}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: vault-ui
  namespace: vault
  labels:
    app: vault
  annotations:
    kubernetes.io/ingress.class: traefik
    forecastle.stakater.com/expose: "true"
    forecastle.stakater.com/group: "Secrets"
    forecastle.stakater.com/icon: "https://cdn.freebiesupply.com/logos/large/2x/vault-enterprise-logo-png-transparent.png"
    forecastle.stakater.com/appName: Vault
spec:
  rules:
    - host: vault.cluster.local
      http:
        paths:
          - backend:
              serviceName: vault
              servicePort: 8200
            path: /
