apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: kube-state-metrics
  namespace: kube-system
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: kube-state-metrics
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: kube-state-metrics
    version: 2.5.0
  valuesFrom:
    - externalSourceRef:
        url: https://raw.githubusercontent.com/REBELinBLUE/k3s-on-raspbian/master/deployments/kube-system/kube-state-metrics/kube-state-metrics-values.yaml