apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: media
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: sonarr
  chart:
    repository: https://bananaspliff.github.io/geek-charts
    name: sonarr
    version: 0.1.0
  valuesFrom:
    - externalSourceRef:
        url: https://raw.githubusercontent.com/REBELinBLUE/k8s-on-hypriot/master/deployments/media/sonarr/sonarr-values.yaml
