helmOperator:
  create: false
git:
  url: "git@github.com:rebelinblue/k8s-on-hypriot.git"
  branch: master
  path: deployments
image:
  repository: onedr0p/flux
  tag: latest-arm32
  pullPolicy: Always
registry:
  rps: 1
  burst: 1
memcached:
  enabled: true
prometheus:
  enabled: true
syncGarbageCollection:
  enabled: true
  dry: false