replicaCount: 1

env:
  - name: PUID
    value: "1000"
  - name: PGID
    value: "1000"

image:
  repository: linuxserver/radarr
  tag: preview
  pullPolicy: Always

service:
  type: ClusterIP
  port: 7878

ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: traefik
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
  path: /
  hosts:
    - radarr.cluster.rebelinblue.com
  tls:
    - hosts:
        - radarr.cluster.rebelinblue.com
      secretName: radarr-tls

volumes:
  - name: media
    persistentVolumeClaim:
      claimName: media
  - name: files
    nfs:
      path: /nfs/Media
      server: 192.168.1.112

volumeMounts:
  - name: media
    mountPath: /config
    subPath: radarr
  - name: files
    mountPath: /media/NAS

resources:
  requests:
    memory: 128Mi
    cpu: 0.1
  limits:
    memory: 256Mi
    cpu: 0.5
