---
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-ingress-configmap
  namespace: infra
data:
  traefik.toml: |
    [global]
      checkNewVersion = true
      sendAnonymousUsage = true

    [entryPoints]
      [entryPoints.http]
        address = ":80"

      [entryPoints.https]
        address = ":443"

      [entryPoints.traefik]
        address = ":8080"

    [providers]
      providersThrottleDuration = "2s"

      [providers.kubernetesIngress]
        throttleDuration = "0s"

        [providers.kubernetesIngress.ingressEndpoint]
          publishedService = "infra/traefik"

    [api]
      insecure = true
      dashboard = true

    [metrics]
      [metrics.prometheus]
        buckets = [0.1, 0.3, 1.2, 5.0]
        entryPoint = "traefik"

    [ping]
      entryPoint = "http"

    [log]
      level = "INFO"
