---
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-ingress-configmap
  namespace: infra
data:
  traefik.toml: |
    defaultEntryPoints = ["http","https"]

    [entryPoints]

      [entryPoints.http]
      address = ":80"

      [entryPoints.https]
      address = ":443"
        [entryPoints.https.tls]
          [[entryPoints.https.tls.certificates]]
          CertFile = "/ssl/tls.crt"
          KeyFile = "/ssl/tls.key"

      [entryPoints.traefik]
        address = ":8080"
        #        [entryPoints.traefik.auth.basic]
        #        users = ["admin:$apr1$0csMKt3r$sX/.atPLDHTpyHGquWmQX."]

    [kubernetes]
      [kubernetes.ingressEndpoint]
        publishedService = "infra/traefik-ingress-controller-http-service"

    [ping]
    entryPoint = "http"

    [api]
    entryPoint = "traefik"

    [metrics]
      [metrics.prometheus]
        entryPoint = "traefik"
        buckets = [0.1,0.3,1.2,5.0]

