---
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-ingress-configmap
  namespace: infra
data:
  traefik.toml: |
    defaultEntryPoints = ["http", "https"]

    #[acme]
    #  email = "letsencrypt@stephen.rebelinblue.com"
    #  entryPoint = "https"
    #  acmeLogging = true
    #  storage = "traefik-external-certificates/acme/account"
    #  OnHostRule = true
    #
    #  [acme.httpChallenge]
    #    entryPoint = "http"
    #
    #  #[acme.dnsChallenge]
    #  #  provider = "linodev4"
    #
    #  #[[acme.domains]]
    #  #  main = "*.cluster.rebelinblue.com"

    [consul]
      endpoint = "consul.infra.svc:8500"
      watch = true
      prefix = "traefik"

    [entryPoints]
      [entryPoints.http]
        address = ":80"

      [entryPoints.https]
        address = ":443"

        [entryPoints.https.tls]
        #  [[entryPoints.https.tls.certificates]]
        #  CertFile = "/ssl/tls.crt"
        #  KeyFile = "/ssl/tls.key"

      [entryPoints.traefik]
        address = ":8080"

    [kubernetes]
      [kubernetes.ingressEndpoint]
        publishedService = "infra/traefik-ingress-controller-http-service"

    [ping]
      entryPoint = "http"

    [api]
      entryPoint = "traefik"

    [metrics]
      [metrics.prometheus]
        entryPoint = "traefik"
        buckets = [0.1,0.3,1.2,5.0]

