---
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-ingress-configmap
  namespace: infra
data:
  traefik.toml: |
    logLevel = "INFO"
    defaultEntryPoints = ["http", "https"]

    [entryPoints]
      [entryPoints.http]
        address = ":80"

      [entryPoints.https]
        address = ":443"

        [entryPoints.https.tls]

      [entryPoints.traefik]
        address = ":8080"

    [kubernetes]
      [kubernetes.ingressEndpoint]
        publishedService = "infra/traefik-ingress-controller-http-service"

    [ping]
      entryPoint = "http"

    [api]
      entryPoint = "traefik"

    [metrics]
      [metrics.prometheus]
        entryPoint = "traefik"
        buckets = [0.1,0.3,1.2,5.0]

