---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: infra
  name: traefik
  labels:
    app: traefik
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      nodeSelector:
        beta.kubernetes.io/arch: arm
        node-role.kubernetes.io/master: "true"
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
      serviceAccountName: traefik-ingress-controller
      terminationGracePeriodSeconds: 35
      volumes:
        - name: traefik-ingress-configmap
          configMap:
            name: traefik-ingress-configmap
      containers:
        - name: traefik
          image: traefik:v2.0
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 200m
              memory: 384Mi
            requests:
              cpu: 25m
              memory: 128Mi
#          livenessProbe:
#            failureThreshold: 2
#            httpGet:
#              path: /ping
#              port: 80
#              scheme: HTTP
#            initialDelaySeconds: 10
#            periodSeconds: 5
#          readinessProbe:
#            failureThreshold: 2
#            httpGet:
#              path: /ping
#              port: 80
#              scheme: HTTP
#            periodSeconds: 5
          args:
            - --configfile=/config/traefik.toml
          ports:
            - name: http
              containerPort: 80
              hostPort: 80
            - name: https
              containerPort: 443
              hostPort: 443
            - name: dashboard
              containerPort: 8080
              hostPort: 8080
          volumeMounts:
            - mountPath: "/config"
              name: traefik-ingress-configmap
