---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: traefik-ingress-controller-dashboard-ingress
  namespace: infra
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    ingress.kubernetes.io/auth-type: basic
    ingress.kubernetes.io/auth-secret: dashboards-auth
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    traefik.ingress.kubernetes.io/redirect-permanent: "true"
spec:
  rules:
    - host: traefik.cluster.rebelinblue.com
      http:
        paths:
        - path: /
          backend:
            serviceName: traefik-ingress-controller-dashboard-service
            servicePort: 8080
  tls:
    - hosts:
        - traefik.cluster.rebelinblue.com
      secretName: traefik-tls