---
apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: infra
spec:
  ports:
    - protocol: TCP
      name: web
      port: 80
    - protocol: TCP
      name: websecure
      port: 443
  selector:
    app: traefik
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-admin
  namespace: infra
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      name: dashboard
      port: 8080
  selector:
    app: traefik
