apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: eventrouter
  namespace: kube-system
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: eventrouter
  chart:
    repository: https://charts.helm.sh/stable
    name: eventrouter
    version: 0.2.3
  valuesFrom:
    - externalSourceRef:
        url: https://raw.githubusercontent.com/REBELinBLUE/k3s-on-raspbian/master/deployments/kube-system/eventrouter/eventrouter-values.yaml
