apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: eventrouter
  namespace: kube-system
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: eventrouter
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: eventrouter
    version: 0.2.3
  valuesFrom:
    - externalSourceRef:
        url: https://raw.githubusercontent.com/REBELinBLUE/k8s-on-hypriot/master/deployments/kube-system/eventrouter/eventrouter-values.yaml