apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitoring
  namespace: infra
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: monitoring
subjects:
  - kind: ServiceAccount
    name: monitoring
    namespace: infra
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-claim
  namespace: infra
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prometheus
  namespace: infra
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: prometheus-server
        blinktShow: "true"
        blinktColor: "00ff00"
    spec:
      serviceAccountName: monitoring
      initContainers:
        - name: init-chown-data
          image: busybox:latest
          imagePullPolicy: IfNotPresent
          # 65534 is the nobody user that prometheus uses.
          command: ["chown", "-R", "65534:65534", "/prometheus/"]
          volumeMounts:
            - name: prometheus-storage-volume
              mountPath: /prometheus/
      containers:
        - name: prometheus
          image: prom/prometheus:v2.13.1
          imagePullPolicy: Always
          args:
            - --config.file=/etc/prometheus/prometheus.yaml
            - --storage.tsdb.retention.time=360h
            - --storage.tsdb.path=/prometheus/
            - --storage.tsdb.no-lockfile
            - --web.enable-lifecycle
            - --web.enable-admin-api
            - --web.external-url=http://prometheus.cluster.rebelinblue.com
          ports:
            - name: prometheus
              containerPort: 9090
          volumeMounts:
            - name: prometheus-config-volume
              mountPath: /etc/prometheus/
            - name: prometheus-storage-volume
              mountPath: /prometheus/
        - name: prometheus-reload
          image: carlosedp/configmap-reload:v0.2.2-arm
          args:
            - --volume-dir=/etc/prometheus/
            - --webhook-url=http://127.0.0.1:9090/-/reload
          volumeMounts:
            - name: prometheus-config-volume
              mountPath: /etc/prometheus/
      volumes:
        - name: prometheus-config-volume
          configMap:
            name: prometheus-config
        - name: prometheus-storage-volume
          persistentVolumeClaim:
            claimName: prometheus-claim
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: infra
  labels:
    name: prometheus
  annotations:
    prometheus.io/scrape: "true"
spec:
  selector:
    app: prometheus-server
  ports:
    - name: prometheus
      port: 8080
      targetPort: prometheus
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: prometheus
  namespace: infra
  annotations:
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    traefik.ingress.kubernetes.io/redirect-permanent: "true"
    kubernetes.io/ingress.class: traefik
    forecastle.stakater.com/expose: "true"
    forecastle.stakater.com/group: "Prometheus"
    forecastle.stakater.com/icon: "https://raw.githubusercontent.com/stakater/ForecastleIcons/master/prometheus.png"
spec:
  rules:
    - host: prometheus.cluster.rebelinblue.com
      http:
        paths:
          - path: /
            backend:
              serviceName: prometheus
              servicePort: 8080
