---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: blinkt-k8s-controller-sa
  namespace: infra
  labels:
    app: blinkt-k8s-controller-sa
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: blinkt-k8s-controller-sa
  labels:
    app: blinkt-k8s-controller-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: blinkt-k8s-controller-sa
    namespace: infra
---
kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: blinkt-k8s-controller-pods
  namespace: infra
spec:
  template:
    metadata:
      labels:
        name: blinkt-k8s-controller-pods
    spec:
      tolerations:
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"
      serviceAccountName: blinkt-k8s-controller-sa
      nodeSelector:
        blinktImage: pods
      containers:
        - name: blinkt-k8s-controller-pods
          image: elafargue/blinkt-k8s-controller-pods:v1
          args:
            - -brightness=0.25
            - -resync_period=10s
            - -namespace=default
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - mountPath: /sys
              name: sys-tree
      volumes:
        - name: sys-tree
          hostPath:
            path: /sys

---
kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: blinkt-k8s-controller-nodes
  namespace: infra
spec:
  template:
    metadata:
      labels:
        name: blinkt-k8s-controller-nodes
    spec:
      tolerations:
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"
      serviceAccountName: blinkt-k8s-controller-sa
      nodeSelector:
        blinktImage: nodes
      containers:
        - name: blinkt-k8s-controller-nodes
          image: elafargue/blinkt-k8s-controller-nodes:v1
          args:
            - -brightness=0.25
            - -resync_period=10s
          volumeMounts:
            - mountPath: /sys
              name: sys-tree
      volumes:
        - name: sys-tree
          hostPath:
            path: /sys
---