---
apiVersion: v1
kind: Namespace
metadata:
  name: media
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media
  namespace: media
spec:
  storageClassName: nfs-hdd
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 150Gi