apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: flux-web
  namespace: flux
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: flux-web
  chart:
    git: git@github.com:flux-web/flux-web.git
    path: chart/flux-web
    ref: master
  valuesFrom:
    - externalSourceRef:
        url: https://raw.githubusercontent.com/REBELinBLUE/k8s-on-hypriot/master/deployments/flux/fluxweb/fluxweb-values.yaml