provisionerName: nfs-provisioner/nfs-hdd

image:
  repository: quay.io/external_storage/nfs-client-provisioner-arm
  tag: v3.1.0-k8s1.11

nfs:
  server: 10.0.0.1
  path: /media/usb

storageClass:
  name: nfs-hdd
  defaultClass: false
