apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nfs-client-provisioner
  namespace: infra
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: nfs-client-provisioner
  chart:
    repository: https://charts.helm.sh/stable
    name: nfs-client-provisioner
    version: 1.2.8
  valuesFrom:
    - externalSourceRef:
        url: https://raw.githubusercontent.com/REBELinBLUE/k3s-on-raspbian/master/deployments/infra/nfs-client-provisioner/nfs-client-provisioner-values.yaml
