apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nfs-client-provisioner
  namespace: infra
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: semver:~v3.1
spec:
  releaseName: nfs-client-provisioner
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: nfs-client-provisioner
    version: 1.2.8
  values:
    provisionerName: nfs-provisioner/nfs-hdd
    image:
      repository: quay.io/external_storage/nfs-client-provisioner-arm
      tag: v3.1.0-k8s1.11
    nfs:
      server: 10.0.0.1
      path: /media/usb
    storageClass:
      name: nfs-hdd
      defaultClass: true
