kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager
  namespace: monitoring
data:
  config.yml: |-
    global:
      resolve_timeout: 5m
      slack_api_url: 'SLACK_URL'

    templates:
      - '/etc/alertmanager-templates/*.tmpl'

    route:
      group_by: ['alertname', 'cluster', 'service']
      group_wait: 10s
      group_interval: 1m
      repeat_interval: 5m
      receiver: default
      routes:
        - match:
            severity: critical
          receiver: critical
          continue: true
        - match:
            severity: warning
          receiver: warning
          continue: true

    receivers:
      - name: 'default'

      - name: 'critical'
        slack_configs:
          - channel: '#k8s-alerts'
            send_resolved: true
            username: '{{ template "slack.default.username" . }}'
            color: '{{ if eq .Status "firing" }}danger{{ else }}good{{ end }}'
            title: '{{ template "slack.default.title" . }}'
            title_link: '{{ template "slack.default.titlelink" . }}'
            pretext: '{{ .CommonAnnotations.summary }}'
            text: |-
              {{ range .Alerts }}
              *Alert:* {{ .Annotations.summary }}
              *Description:* {{ .Annotations.description }}
              *Details:*
              {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
              {{ end }}
              *Source:* {{ .GeneratorURL }}
              {{ end }}
            fallback: '{{ template "slack.default.fallback" . }}'
            icon_emoji: '{{ template "slack.default.iconemoji" . }}'
            icon_url: '{{ template "slack.default.iconurl" . }}'

      - name: 'warning'
        slack_configs:
          - channel: '#k8s-alerts'
            send_resolved: true
            username: '{{ template "slack.default.username" . }}'
            color: '{{ if eq .Status "firing" }}danger{{ else }}good{{ end }}'
            title: '{{ template "slack.default.title" . }}'
            title_link: '{{ template "slack.default.titlelink" . }}'
            pretext: '{{ .CommonAnnotations.summary }}'
            text: |-
              {{ range .Alerts }}
              *Alert:* {{ .Annotations.summary }}
              *Description:* {{ .Annotations.description }}
              *Details:*
              {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
              {{ end }}
              *Source:* {{ .GeneratorURL }}
              {{ end }}
            fallback: '{{ template "slack.default.fallback" . }}'
            icon_emoji: '{{ template "slack.default.iconemoji" . }}'
            icon_url: '{{ template "slack.default.iconurl" . }}'
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alertmanager-claim
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: alertmanager
  template:
    metadata:
      annotations:
        SECRET_SLACK_URL: /apps/shared/slack/slack_url
      labels:
        k8s-app: alertmanager
    spec:
      initContainers:
        - name: init
          image: rebelinblue/vault-consumer:0.0.2
          command:
            - sh
            - -c
          args:
            - /entrypoint.sh confd;
              source /env/secrets;
              sed "s#SLACK_URL#$SLACK_URL#g" /tmp/config/config.yml > /etc/alertmanager/config.yml
          env:
            - name: VAULT_ROLE_ID
              valueFrom:
                secretKeyRef:
                  key: role_id
                  name: alertmanager-approle
            - name: VAULT_SECRET_ID
              valueFrom:
                secretKeyRef:
                  key: secret_id
                  name: alertmanager-approle
          volumeMounts:
            - mountPath: /env
              name: env
            - mountPath: /tmpfs
              name: podinfo
            - name: config-volume
              mountPath: /tmp/config
            - name: config
              mountPath: /etc/alertmanager
      containers:
        - name: alertmanager
          image: prom/alertmanager:v0.19.0
          imagePullPolicy: Always
          args:
            - --config.file=/etc/alertmanager/config.yml
            - --storage.path=/alertmanager
            - --web.external-url=http://alertmanager.cluster.rebelinblue.com
          ports:
            - name: alertmanager
              containerPort: 9093
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
          volumeMounts:
            - name: config
              mountPath: /etc/alertmanager
            - name: alertmanager
              mountPath: /alertmanager
      volumes:
        - name: config-volume
          configMap:
            name: alertmanager
        - name: config
          emptyDir: {}
        - name: alertmanager
          persistentVolumeClaim:
            claimName: alertmanager-claim
        - name: env
          emptyDir: {}
        - name: podinfo
          downwardAPI:
            defaultMode: 420
            items:
              - fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.annotations
                path: annotations
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: monitoring
  labels:
    name: alertmanager
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/metrics'
spec:
  selector:
    k8s-app: alertmanager
  ports:
    - name: alertmanager
      protocol: TCP
      port: 9093
      targetPort: 9093
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: alertmanager
  namespace: monitoring
  labels:
    name: alertmanager
  annotations:
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: letsencrypt-staging
    ingress.kubernetes.io/auth-type: forward
    ingress.kubernetes.io/auth-url: http://traefik-forward-auth.infra.svc
    ingress.kubernetes.io/auth-response-headers: X-Forwarded-User
spec:
  rules:
    - host: alertmanager.cluster.rebelinblue.com
      http:
        paths:
          - path: /
            backend:
              serviceName: alertmanager
              servicePort: 9093
  tls:
    - hosts:
        - alertmanager.cluster.rebelinblue.com
      secretName: alertmanager-tls
---
