---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: monitoring
  name: chronograf
  labels:
    app: chronograf
data:
  monitor.src: |-
  {
    "id": "5000",
    "name": "internal",
    "url": "http://influxdb.monitoring.svc:8086",
    "type": "influx",
    "insecureSkipVerify": false,
    "default": true,
    "telegraf": "cloud",
    "organization": "influx"
  }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chronograf
  namespace: monitoring
  labels:
    app: chronograf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chronograf
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: chronograf
    spec:
      containers:
        - name: chronograf
          image: arm32v7/chronograf:1.7.14
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8888
              name: api
          livenessProbe:
            httpGet:
              path: /ping
              port: api
          readinessProbe:
            httpGet:
              path: /ping
              port: api
          volumeMounts:
            - name: data
              mountPath: /var/lib/chronograf
            - name: config
              mountPath: /usr/share/chronograf/resources
          resources:
            limits:
              cpu: 2
              memory: 2Gi
            requests:
              cpu: 0.1
              memory: 256Mi
      volumes:
        - name: config
          configMap:
            name: chronograf
        - name: data
          persistentVolumeClaim:
            claimName: chronograf
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chronograf
  namespace: monitoring
  labels:
    app: chronograf
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: Service
metadata:
  name: chronograf
  namespace: monitoring
  labels:
    app: chronograf
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8888
  selector:
    app: chronograf
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: chronograf
  namespace: monitoring
  labels:
    app: chronograf
  annotations:
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    ingress.kubernetes.io/auth-type: basic
    ingress.kubernetes.io/auth-secret: dashboards-auth
spec:
  rules:
    - host: chronograf.cluster.rebelinblue.com
      http:
        paths:
          - path: /
            backend:
              serviceName: chronograf
              servicePort: 80
  tls:
    - hosts:
        - chronograf.cluster.rebelinblue.com
      secretName: chronograf-tls