apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: helm-operator
  namespace: flux
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: helm-operator
  chart:
    repository: https://charts.fluxcd.io/
    name: helm-operator
    version: 0.7.0
  valuesFrom:
    - externalSourceRef:
        url: https://raw.githubusercontent.com/REBELinBLUE/k8s-on-hypriot/master/deployments/flux/helm-operator/helm-operator-values.yaml