createCRD: false

git:
  ssh:
    secretName: flux-git-deploy

image:
  repository: rebelinblue/helm-operator
  tag: 1.0.1
  pullPolicy: Always

chartsSyncInterval: "5m"
statusUpdateInterval: "5m"

prometheus:
  enabled: true
  serviceMonitor:
    create: true

helm:
  versions: "v3"

extraEnvs:
  - name: HELM_VERSION
    value: v3