createCRD: false

git:
  ssh:
    secretName: flux-git-deploy

image:
  repository: rebelinblue/helm-operator
  tag: 1.2.0
  pullPolicy: Always

chartsSyncInterval: "5m"
statusUpdateInterval: "5m"

prometheus:
  enabled: true
  serviceMonitor:
    create: true

helm:
  versions: "v3"

extraEnvs:
  - name: HELM_VERSION
    value: v3

resources:
  limits:
    cpu: 300m
    memory: 500Mi
  requests:
    cpu: 50m
    memory: 64Mi
