createCRD: true

git:
  ssh:
    secretName: flux-git-deploy

image:
  repository: rebelinblue/helm-operator
  tag: v1.0.0-rc7
  pullPolicy: Always

chartsSyncInterval: "5m"
statusUpdateInterval: "5m"

prometheus:
  enabled: true

helm:
  versions: "v3"

extraEnvs:
  - name: HELM_VERSION
    value: v3