apiVersion: forecastle.stakater.com/v1alpha1
kind: ForecastleApp
metadata:
  name: tautulli
  namespace: media
spec:
  name: Tautulli
  group: Media
  icon: https://avatars1.githubusercontent.com/u/34385001
  networkRestricted: true
  urlFrom:
    ingressRef:
      name: tautulli