createCRD: true
git:
  ssh:
    secretName: flux-git-deploy
image:
  repository: onedr0p/helm-operator
  tag: latest-arm32
  pullPolicy: Always
chartsSyncInterval: "5m"
statusUpdateInterval: "5m"
prometheus:
  enabled: true