---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: popeye
  namespace: popeye
spec:
  schedule: "* */1 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: popeye
          restartPolicy: OnFailure
          containers:
            - name: popeye
              image: rebelinblue/popeye:v0.8.0
              imagePullPolicy: IfNotPresent
              command: ["/bin/popeye"]
              args:
                - -f
                - /etc/config/popeye/spinach.yml
                - -o
                - standard
              resources:
                limits:
                  cpu: 500m
                  memory: 100Mi
              volumeMounts:
                - name: spinach
                  mountPath: /etc/config/popeye
          volumes:
            - name: spinach
              configMap:
                name: popeye
                items:
                  - key: spinach
                    path: spinach.yml