---
kind: Service
apiVersion: v1
metadata:
  name: fluxcloud
  namespace: flux
spec:
  selector:
    name: fluxcloud
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3032
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluxcloud
  namespace: flux
spec:
  replicas: 1
  selector:
    matchLabels:
      name: fluxcloud
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        SECRET_SLACK_URL: /apps/shared/slack/slack_url
      labels:
        name: fluxcloud
    spec:
      initContainers:
        - name: init
          image: rebelinblue/vault-consumer:0.0.2
          imagePullPolicy: IfNotPresent
          env:
            - name: VAULT_ROLE_ID
              valueFrom:
                secretKeyRef:
                  key: role_id
                  name: fluxcloud-approle
            - name: VAULT_SECRET_ID
              valueFrom:
                secretKeyRef:
                  key: secret_id
                  name: fluxcloud-approle
          volumeMounts:
            - mountPath: /env
              name: env
            - mountPath: /tmpfs
              name: podinfo
      containers:
        - name: fluxcloud
          image: rebelinblue/fluxcloud:0.3.9
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3032
          command:
            - sh
            - -c
          args:
            - source /env/secrets; /fluxcloud
          env:
            - name: SLACK_CHANNEL
              value: "#k8s-alerts"
            - name: SLACK_USERNAME
              value: Flux Deployer
            - name: SLACK_ICON_EMOJI
              value: ":heart:"
            - name: GITHUB_URL
              value: "https://github.com/REBELinBLUE/k3s-on-raspbian/"
            - name: LISTEN_ADDRESS
              value: ":3032"
          volumeMounts:
            - mountPath: /env
              name: env
      volumes:
        - name: env
          emptyDir: {}
        - name: podinfo
          downwardAPI:
            defaultMode: 420
            items:
              - fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.annotations
                path: annotations