---
kind: Service
apiVersion: v1
metadata:
  name: fluxcloud
  namespace: flux
spec:
  selector:
    name: fluxcloud
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3032
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluxcloud
  namespace: flux
spec:
  replicas: 1
  selector:
    matchLabels:
      name: fluxcloud
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: fluxcloud
    spec:
      securityContext:
        runAsUser: 999
      containers:
        - name: fluxcloud
          image: rebelinblue/fluxcloud:0.3.9
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3032
          env:
            - name: SLACK_URL
              valueFrom:
                secretKeyRef:
                  name: fluxcloud
                  key: slack_url
            - name: SLACK_CHANNEL
              value: "#k8s-alerts"
            - name: SLACK_USERNAME
              value: Flux Deployer
            - name: SLACK_ICON_EMOJI
              value: ":heart:"
            - name: GITHUB_URL
              value: "https://github.com/REBELinBLUE/k8s-on-hypriot/"
            - name: LISTEN_ADDRESS
              value: ":3032"