apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: kube-system
  annotations:
    fluxcd.io/automated: "false"
    fluxcd.io/tag.chart-image: semver:~0
spec:
  releaseName: metrics-server
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: metrics-server
    version: 0.2.3
  values:
    image:
      repository: k8s.gcr.io/metrics-server-arm
      tag: v0.3.6
    args:
      - --kubelet-insecure-tls
      - --kubelet-preferred-address-types=InternalIP
