apiVersion: v1
kind: ConfigMap
metadata:
  name: blackbox-exporter
  namespace: monitoring
  labels:
    app: blackbox-exporter
data:
  blackbox.yaml: |
    modules:
      http_2xx:
        prober: http
        timeout: 5s
        http:
          no_follow_redirects: true
          preferred_ip_protocol: ip4
          valid_http_versions:
            - HTTP/1.1
            - HTTP/2
          valid_status_codes:
            - 200
            - 301
            - 307
            - 401
            - 403
---
apiVersion: v1
kind: Service
metadata:
  name: blackbox-exporter
  namespace: monitoring
  labels:
    app: blackbox-exporter
  annotations:
    prometheus.io/scrape: 'true'
spec:
  ports:
    - name: http
      port: 9115
      protocol: TCP
      targetPort: 9115
  selector:
    app: blackbox-exporter
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: blackbox-exporter
  namespace: monitoring
  labels:
    name: blackbox-exporter
  annotations:
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    ingress.kubernetes.io/auth-type: basic
    ingress.kubernetes.io/auth-secret: dashboards-auth
spec:
  rules:
    - host: blackbox.cluster.rebelinblue.com
      http:
        paths:
          - path: /
            backend:
              serviceName: blackbox-exporter
              servicePort: 9115
  tls:
    - hosts:
        - blackbox.cluster.rebelinblue.com
      secretName: blackbox-exporter-tls
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: blackbox-exporter
  namespace: monitoring
  labels:
    app: blackbox-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blackbox-exporter
  template:
    metadata:
      labels:
        app: blackbox-exporter
        blinktShow: "true"
        blinktColor: "00ff00"
    spec:
      containers:
        - name: prometheus-blackbox-exporter
          image: lwolf/blackbox-exporter:v0.16.0-armv6
          imagePullPolicy: IfNotPresent
          args:
            - --config.file=/etc/config/blackbox.yaml
          ports:
            - containerPort: 9115
              name: http
              protocol: TCP
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: http
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: http
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          securityContext:
            procMount: Default
            readOnlyRootFilesystem: true
          volumeMounts:
            - mountPath: /etc/config
              name: config
      volumes:
        - configMap:
            defaultMode: 420
            name: blackbox-exporter
          name: config
---
