---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: forecastle
  namespace: apps
  labels:
    app: forecastle
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: forecastle
  template:
    metadata:
      labels:
        app: forecastle
    spec:
      containers:
      - name: forecastle
        image: rebelinblue/forecastle:1.0.36
        env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        volumeMounts:
          - name: forecastle-config
            mountPath: /etc/forecastle
      volumes:
        - name: forecastle-config
          configMap:
            name: forecastle
      serviceAccountName: forecastle
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: forecastle
  namespace: apps
  labels:
    app: forecastle
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: forecastle-cluster-ingress-role
  namespace: apps
  labels:
    app: forecastle
rules:
  - apiGroups: ["", "extensions"]
    resources: ["ingresses", "namespaces"]
    verbs: ["get", "list"]
  - apiGroups: ["forecastle.stakater.com"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: forecastle-cluster-ingress-role-binding
  namespace: apps
  labels:
    app: forecastle
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: forecastle-cluster-ingress-role
subjects:
  - kind: ServiceAccount
    name: forecastle
    namespace: apps
---
apiVersion: v1
kind: Service
metadata:
  name: forecastle
  namespace: apps
  labels:
    app: forecastle
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: forecastle
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: forecastle
  namespace: apps
  labels:
    app: forecastle
data:
  config.yaml: |-
    customApps: {}
    headerBackground: null
    headerForeground: null
    instanceName: null
    crdEnabled: true
    namespaceSelector:
      matchNames:
        - logging
        - monitoring
        - kubernetes-dashboard
        - apps
        - infra
        - kube-system
        - devops
        - vault
    title: Launch Pad
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: forecastle
  namespace: apps
  annotations:
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
    - host: launchpad.cluster.rebelinblue.com
      http:
        paths:
          - path: /
            backend:
              serviceName: forecastle
              servicePort: 80
  tls:
    - hosts:
        - launchpad.cluster.rebelinblue.com
      secretName: forecastle-tls
